### ISSUE TITLE
KeePassXC freezes upon vault unlock

### ISSUE THREAD

**Issue by fe6865d3bf** [purejava/keepassxc-cryptomator#4]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-cryptomator/issues?q=) for duplicates

### Summary

Cryptomator and KeePassXC freeze upon vault unlock

### What software is involved?

- Operating System: Windows 10
- Cryptomator: 1.6.1
- keepassxc-cryptomator-0.0.3.jar
- KeePassXC: 2.6.6

### Steps to Reproduce

1. Install plugin
2. Set "Store passwords with" to KeePassXC
3. Unlock KeePassXC
4. Press on vault name to unlock

### Expected Behavior

1. KeePassXC association request successful
2. Vault unlocks

### Actual Behavior

Cryptomator and KeepassXC freeze when "KeePassXC:New key association request" window pop up

### Reproducibility

Always

### Relevant Log Output

```shell
12:59:03.446 [main] INFO  org.cryptomator.launcher.Cryptomator - Starting Cryptomator 1.6.1 on Windows 10 10.0 (amd64)
12:59:03.455 [main] DEBUG org.cryptomator.logging.DebugMode - Debug mode enabled
12:59:03.497 [main] WARN  org.cryptomator.ipc.IpcCommunicator - Failed to create IPC server
java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.UnixDomainSockets.bind0(Native Method)
	at java.base/sun.nio.ch.UnixDomainSockets.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.unixBind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/java.nio.channels.ServerSocketChannel.bind(Unknown Source)
	at org.cryptomator.desktop@1.6.1/org.cryptomator.ipc.Server.create(Server.java:33)
	at org.cryptomator.desktop@1.6.1/org.cryptomator.ipc.IpcCommunicator.create(IpcCommunicator.java:47)
	at org.cryptomator.desktop@1.6.1/org.cryptomator.launcher.Cryptomator.run(Cryptomator.java:77)
	at org.cryptomator.desktop@1.6.1/org.cryptomator.launcher.Cryptomator.main(Cryptomator.java:57)
12:59:03.539 [main] DEBUG o.c.launcher.IpcMessageHandler - Received launch args: 
12:59:03.540 [main] DEBUG org.cryptomator.launcher.Cryptomator - Did not find running application instance. Launching GUI...
12:59:03.899 [main] DEBUG org.cryptomator.common.CommonsModule - Starting App Scheduled Executor 01
12:59:03.906 [App Scheduled Executor 01] DEBUG org.cryptomator.common.CommonsModule - Starting App Scheduled Executor 02
12:59:04.126 [main] DEBUG o.c.ui.traymenu.TrayIconController - initialized tray icon
12:59:04.129 [main] DEBUG o.cryptomator.ui.launcher.UiLauncher - Showing application...
12:59:04.129 [main] DEBUG org.cryptomator.common.CommonsModule - Starting App Background Thread 001
12:59:04.130 [App Background Thread 001] DEBUG o.c.ui.launcher.FxApplicationStarter - Starting JavaFX runtime...
12:59:04.132 [main] DEBUG org.cryptomator.common.CommonsModule - Starting App Background Thread 002
12:59:04.300 [JavaFX Application Thread] INFO  o.c.ui.launcher.FxApplicationStarter - JavaFX Runtime started.
12:59:04.334 [JavaFX Application Thread] TRACE o.cryptomator.ui.fxapp.FxApplication - FxApplication.start()
12:59:04.700 [JavaFX Application Thread] DEBUG org.cryptomator.ui.common.FontLoader - Loaded family: Font Awesome 5 Free Solid
12:59:04.714 [JavaFX Application Thread] TRACE o.c.u.m.MainWindowTitleController - init MainWindowTitleController
12:59:04.823 [JavaFX Application Thread] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 1, Database not opened
12:59:04.874 [JavaFX Application Thread] TRACE o.c.ui.mainwindow.ResizeController - init ResizeController
12:59:04.877 [JavaFX Application Thread] TRACE o.c.u.m.MainWindowController - init MainWindowController
12:59:04.904 [JavaFX Application Thread] DEBUG o.cryptomator.ui.fxapp.FxApplication - has visible stages: true
12:59:05.145 [JavaFX Application Thread] DEBUG o.cryptomator.ui.fxapp.FxApplication - Showing MainWindow
12:59:08.140 [JavaFX Application Thread] DEBUG o.c.f.fuse.mount.WindowsMounter - Failed to find a WinFsp installation; that's only a problem if you want to use FUSE on Windows. Exception text: "Can't find winfsp library. Please make sure that winfsp is installed or configure the path to dll manually using the `jnrfuse.winfsp.path` property"
12:59:08.285 [JavaFX Application Thread] DEBUG o.cryptomator.ui.fxapp.FxApplication - Showing Preferences
12:59:09.082 [App Scheduled Executor 01] DEBUG o.c.common.settings.SettingsProvider - Attempting to save settings to C:\Users\User\AppData\Roaming\Cryptomator\settings.json
12:59:09.103 [App Scheduled Executor 01] INFO  o.c.common.settings.SettingsProvider - Settings saved to C:\Users\User\AppData\Roaming\Cryptomator\settings.json
12:59:09.718 [JavaFX Application Thread] DEBUG org.cryptomator.common.CommonsModule - Starting App Background Thread 003
12:59:09.722 [JavaFX Application Thread] DEBUG o.cryptomator.ui.fxapp.UpdateChecker - Checking for updates...
12:59:10.077 [JavaFX Application Thread] INFO  o.cryptomator.ui.fxapp.UpdateChecker - Current version: 1.6.1, lastest version: 1.6.1
12:59:15.951 [App Scheduled Executor 02] DEBUG o.c.common.settings.SettingsProvider - Attempting to save settings to C:\Users\User\AppData\Roaming\Cryptomator\settings.json
12:59:15.960 [App Scheduled Executor 02] INFO  o.c.common.settings.SettingsProvider - Settings saved to C:\Users\User\AppData\Roaming\Cryptomator\settings.json
12:59:58.606 [JavaFX Application Thread] INFO  org.keepassxc.Connection - Received signal database-unlocked
12:59:58.792 [App Scheduled Executor 01] DEBUG o.c.common.settings.SettingsProvider - Attempting to save settings to C:\Users\User\AppData\Roaming\Cryptomator\settings.json
12:59:58.794 [App Scheduled Executor 01] INFO  o.c.common.settings.SettingsProvider - Settings saved to C:\Users\User\AppData\Roaming\Cryptomator\settings.json
```

### Anything else?

![Ft2yhqw](https://user-images.githubusercontent.com/62340811/139419829-99563bf0-e29b-4981-8232-323af47ae4bb.png)

**Comment by purejava** [comment]
Thank you for your bug report! I can reproduce this on Windows 11 too and will investigate this further.

**Comment by purejava** [comment]
Reported bug for [keepassxreboot/keepassxc#7099](https://github.com/keepassxreboot/keepassxc/issues/7099).
I debugged Cryptomator and KeePassXC and consider this to be a Qt bug.
Actually KeePassXC gets the `associate` request and fails to show the association dialog properly, while Cryptomator waits for the `associate` request to be finished or cancelled, which is not possible as the dialog is not displayed completely.

A workaround is to somehow bring up the association dialog completely. One time is enough. From then on, the problem is gone.
This could be done by installing a KeePassXC browser extension and triggering the association dialog from there once.

**Comment by Mayurifag** [comment]
Having the same issue with Windows 10. But no issues on archlinux with the same c9r <-> keepassxc configuration.

**Comment by purejava** [comment]
> Having the same issue with Windows 10, so plugin is unusable. But no issues on archlinux with the same c9r <-> keepassxc configuration.

The problem seems to be Windows specific, see https://github.com/keepassxreboot/keepassxc/issues/7099#issuecomment-981113603.

**Comment by Mayurifag** [comment]
And sorry for writing here things not about the problem, but Im feeling confused to report these elsewhere, I dont see any fast contact. I guess, @purejava you are fine to hotfix that pretty easily. 😄 

Github currently has no way to make PR to Wiki page, so I can't fix the documentation. Its wrong for windows installation path. It has to be not like `~/AppData/Roaming/Cryptomator/Plugins`, but better to be `%APPDATA%\Cryptomator\plugins`, i.e. `C:\Users\Administrator\AppData\Roaming\Cryptomator\plugins` — yea, %APPDATA% points to `...\AppData\Roaming`, path consits of `\`, and not `/` in Windows, and the most noticeable thing that folder has to be created starting with small «p», so it has to be `plugins`, not `Plugins` — c9r wont use plugins from folder `Plugins`.

Also, I wish the message from AUR PKGBUILD, thats about `In order to make it available to Cryptomator, you need to create a symlink to the Cryptomator plugin directory........`, — that has to be message in post-install section. If I didn't read the PKGBUILD itself, I didn't notice that message, because building messages were spammed and totally set message above, so I had to scroll untill there.

Thanks in advance, also hoping this issue with win10 goes away soon. 👍🏻

**Comment by purejava** [comment]
> Github currently has no way to make PR to Wiki page, so I can't fix the documentation. It has wrong installation path for Windows. It has to be not like `~/AppData/Roaming/Cryptomator/Plugins`, but better to be `%APPDATA%\Cryptomator\plugins`, i.e. `C:\Users\Administrator\AppData\Roaming\Cryptomator\plugins` — yea, %APPDATA% points to `...\AppData\Roaming`, path consits of `\`, and not `/` in Windows, and the most noticeable thing that folder has to be created starting with small «p», so it has to be `plugins`, not `Plugins` — c9r wont use plugins from folder `Plugins`.

Thanks for pointing out the wrong installation path for windows in the wiki. It's fixed.

Concerning the uppercase P you are wrong. The path gets defined in Cryptomator, see [Cryptomator_Windows.xml](https://github.com/cryptomator/cryptomator/blob/13e9775458d92f4b0f56891eb10e1fb7d5ad3ad3/.idea/runConfigurations/Cryptomator_Windows.xml#L5):
```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Cryptomator Windows" type="Application" factoryName="Application">
    <option name="MAIN_CLASS_NAME" value="org.cryptomator.launcher.Cryptomator" />
    <module name="cryptomator" />
    <option name="VM_PARAMETERS" value="-Duser.language=en -Dcryptomator.settingsPath=&quot;~/AppData/Roaming/Cryptomator/settings.json&quot; -Dcryptomator.ipcSocketPath=&quot;~/AppData/Roaming/Cryptomator/ipc.socket&quot; -Dcryptomator.logDir=&quot;~/AppData/Roaming/Cryptomator&quot; -Dcryptomator.pluginDir=&quot;~/AppData/Roaming/Cryptomator/Plugins&quot; -Dcryptomator.keychainPath=&quot;~/AppData/Roaming/Cryptomator/keychain.json&quot; -Dcryptomator.mountPointsDir=&quot;~/Cryptomator&quot; -Dcryptomator.showTrayIcon=true -Xss2m -Xmx512m" />
    <method v="2">
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>
```
Nevertheless, both might work as Windows is not case sensitive.
> Also, I wish the message from AUR PKGBUILD, thats about `In order to make it available to Cryptomator, you need to create a symlink to the Cryptomator plugin directory........`, — that has to be message in post-install section. If I didn't read the PKGBUILD itself, I didn't notice that message, because building messages were spammed and totally set message above, so I had to scroll until there.

PRs are welcome. If you want to change the PKGBUILD build description file, please provide a PR. The repository can be found [here](https://github.com/purejava/keepassxc-cryptomator-aur).

> I also wish install instructions to be at README.md itself, without not needed things about building, signatures, etc. — less actions = happier the user. 😆 But its up to you. :)

I disagree. I link in the README.md to the wiki is sufficient from my point of view.

**Comment by purejava** [comment]
I've found a way to circumvent the Qt bug, that works on all platforms. Details can be found [here](https://github.com/keepassxreboot/keepassxc/issues/7099#issuecomment-1022019097).

Designing a solution for this issue as a side-effect led to a major improvement of the keepassxc-cryptomator plugin, as it now works asynchronously.

Testing of the changes is finished now and I'll release an update of keepassxc-cryptomator, that also contains the fix.

**Comment by purejava** [comment]
keepassxc-cryptomator `1.0.0` has been released that fixes this issue.

**Comment by purejava** [comment]
Please use keepassxc-cryptomator `1.0.1`. After all the testing I changed the code before I released `1.0.0` and introduced a bug, that broke the functionality of the plugin. 😊

**Comment by purejava** [comment]
@fe6865d3bf, @Mayurifag, do you have a chance to test keepassxc-cryptomator `1.0.1` and see if the issue is fixed for you?

**Comment by Mayurifag** [comment]
Thanks for your work! ❤️ 
I didn't launch my windows desktop for many-many days, but I'll write if I won't forgot 😄
