### ISSUE TITLE
Unlock database if locked

### ISSUE THREAD

**Issue by scollovati** [purejava/keepassxc-cryptomator#94]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-cryptomator/issues?q=) for duplicates

### Summary

Unlock database if locked

### Motivation

The database may be locked when opening a vault. Currently Cryptomator immediately switches to the password authentication popup. The desidered behaviour is similar to the KeepassXC Browser extension, that redirects the user to KeepassXC for unlocking the database.

**Comment by purejava** [comment]
What do you mean whith "redirects the user to KeepassXC for unlocking the database"?

Are you talking about the button in the extension to unlock the database, that brings the KeePassXC app to the front?

**Comment by scollovati** [comment]
If the database is locked, when you use the browser extension or the Auto-Type shortcut a popup appears for unlocking the database:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/f2277022-0e66-4e28-8fc9-1e29b1ca9a91">

In fact you cannot assume that the db is always unlocked.

**Comment by purejava** [comment]
Thanks for bringing this up @scollovati.

Implemented with 7b6759d70f401c5be4f9fafad213f186172bdc99 and released as version `1.2.6`.
