### ISSUE TITLE
Improve naming of items in KeepassXC

### ISSUE THREAD

**Issue by scollovati** [purejava/keepassxc-cryptomator#95]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-cryptomator/issues?q=) for duplicates

### Summary

Improve naming of items in KeepassXC

### Motivation

I suggest to use the name of the vault as the title of the KeepassXC item, potentially putting the "Vault" word before or after it. In fact [Cryptomator API offers the displayName](https://github.com/cryptomator/integrations-api/blob/develop/src/main/java/org/cryptomator/integrations/keychain/KeychainAccessProvider.java#L67-L69).

This would be useful since KeepassXC uses the title in these popups when updating or deleting an item:

- A request for deleting entry “[TITLE]” has been received.  

- Do you want to update the information in [TITLE] - [USERNAME]?  

By making this change, the key of the vault that now is used as the title, could be put in the username field instead of the [generic "Vault" word](https://github.com/purejava/keepassxc-cryptomator/blame/7b6759d70f401c5be4f9fafad213f186172bdc99/src/main/java/org/purejava/integrations/keychain/KeePassXCAccess.java#L61).

This change should not have any impact on existing Cryptomator credentials in KeepassXC since those are [retrieved via the URL (scheme + vault key)](https://github.com/purejava/keepassxc-cryptomator/blame/7b6759d70f401c5be4f9fafad213f186172bdc99/src/main/java/org/purejava/integrations/keychain/KeePassXCAccess.java#L93).

**Comment by purejava** [comment]
Thanks @scollovati for this suggestion. I would love to implement it and thought about it too on creating this plugin, but unfortunately, it's not possible IMHO.

The plugin communicates with KeePassXC's built-in proxy via the KeePassXC protocol.  Just like the KeePassXC browser extension does.

The message sent to the KeePassXC database on storing a new entry contains the URL of the web page, not even the title of the web page. So the new entry gets created in the database, with the title of the new entry being the hostname of the URL. It's a limitation of the underlying protocol. For more information, see the [keepassxc-protocol](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md#set-login).

**Comment by scollovati** [comment]
@purejava True, I've not looked carefully at the protocol. However using the displayName of the vault instead of a generic "Vault" as the username is possible: https://github.com/purejava/keepassxc-cryptomator/blob/7b6759d70f401c5be4f9fafad213f186172bdc99/src/main/java/org/purejava/integrations/keychain/KeePassXCAccess.java#L78

**Comment by purejava** [comment]
> @purejava True, I've not looked carefully at the protocol. However using the displayName of the vault instead of a generic "Vault" as the username is possible: https://github.com/purejava/keepassxc-cryptomator/blob/7b6759d70f401c5be4f9fafad213f186172bdc99/src/main/java/org/purejava/integrations/keychain/KeePassXCAccess.java#L78

Unfortunately not. Cryptomator sends the `displayName` variable to the plugin, that transfers it to KeePassXC, that ignores it. The field in the protocol that is used by the plugin is an ‘id‘, that's ignored, as said. See here: https://github.com/purejava/keepassxc-proxy-access/blob/3ae6f5b724412acdcb1fb4d7b4600e38b1acfad8/src/main/java/org/purejava/KeepassProxyAccess.java#L301

**Comment by purejava** [comment]
> In my last comment, I am referring to the [login parameter](https://github.com/purejava/keepassxc-proxy-access/blob/3ae6f5b724412acdcb1fb4d7b4600e38b1acfad8/src/main/java/org/purejava/KeepassProxyAccess.java#L302) , that is currently hard-wired as "Vault":
> 
> https://github.com/purejava/keepassxc-cryptomator/blob/7b6759d70f401c5be4f9fafad213f186172bdc99/src/main/java/org/purejava/integrations/keychain/KeePassXCAccess.java#L61

You are right, that can be improved. I misread your previous comment, sorry.

**Comment by purejava** [comment]
Implemented with https://github.com/purejava/keepassxc-cryptomator/commit/2e5c21db4ba9b51ddc756627fb9bd6e657446073 and released as version `1.2.7`.
